config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  root 'readers/home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: 'authors' do 
    resources :posts do 
      resources :elements
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post
  has_rich_text :content
  has_one_attached :image
  has_one_attached :element_video

  def paragraph?
    element_type == "paragraph"
  end

  def image?
    element_type == "image"
  end

  def element_video?
    element_type == "element_video"
  end

end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  belongs_to :author
  has_many :elements
  has_one_attached :header_image

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/elements_controller.rb
module Authors
  class ElementsController < AuthorsController
    before_action :set_post
    before_action :set_element, only: %i[ show edit update destroy ]

    # GET /elements or /elements.json
    def index
      @elements = Element.all
    end

    # GET /elements/1 or /elements/1.json
    def show
    end

    # GET /elements/new
    def new
      @element = Element.new
    end

    # GET /elements/1/edit
    def edit
    end

    # POST /elements or /elements.json
    def create
      @element = @post.elements.build(element_params)
      @element.post_id = @post.id 

      if @element.save
        notice = nil
      else
        notice = @element.errors.full_messages.loin(". ") << "."
      end
      redirect_to edit_post_path(@post)
    end

    # PATCH/PUT /elements/1 or /elements/1.json
    def update
      @element.update(element_params)

      respond_to do |format|
        format.html { redirect_to edit_post_path(@post) }
        format.json { head :no_content }
        format.js { }
      end
    end

    # DELETE /elements/1 or /elements/1.json
    def destroy
      @element.destroy
      respond_to do |format|
        format.html { redirect_to edit_post_path(@element.post), notice: "Element was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

      def set_post
        @post = current_author.posts.find(params[:post_id])
      end
      # Use callbacks to share common setup or constraints between actions.
      def set_element
        @element = Element.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def element_params
        params.require(:element).permit(:element_type, :position, :content, :image, :element_video)
      end
  end

end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: %i[ show edit update destroy ]

    # GET /posts or /posts.json
    def index
      @posts = Post.all
    end

    # GET /posts/1 or /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
      @element = @post.elements.build
    end

    # POST /posts or /posts.json
    def create
      @post = current_author.posts.build(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to edit_post_path(@post), notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to edit_post_path(@post), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1 or /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :description, :published, :header_image)
      end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	before_action :authenticate_author!
	
	layout 'authors'
end

app/controllers/readers/home_controller.rb
module Readers
  class HomeController < ReadersController
    def index
    end
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
	layout 'readers'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/elements/_form.html.erb
<%= form_with(model: element) do |form| %>
  <% if element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
        <% element.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :element_type %>
    <%= form.text_field :element_type %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/elements/edit.html.erb
<h1>Editing Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/authors/elements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elements</h1>

<table>
  <thead>
    <tr>
      <th>Element type</th>
      <th>Post</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td><%= element.element_type %></td>
        <td><%= element.post_id %></td>
        <td><%= element.position %></td>
        <td><%= link_to 'Show', element %></td>
        <td><%= link_to 'Edit', edit_element_path(element) %></td>
        <td><%= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Element', new_element_path %>

app/views/authors/elements/new.html.erb
<h1>New Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Back', elements_path %>

app/views/authors/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Element type:</strong>
  <%= @element.element_type %>
</p>

<p>
  <strong>Post:</strong>
  <%= @element.post_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @element.position %>
</p>

<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>

app/views/authors/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  
  <div class="field">
    <%= form.label :header_image %>
    <%= form.file_field :header_image, class: "form-control" %>
    <div class="mt-1">
      <small>Current image:</small>
      <% if post.header_image.present? %>
        <%= image_tag(post.header_image, width: '100%', class: "mt-1") %>
      <% end %>
    </div>
  </div>
  <br>

  <div class="d-grid gap-2">
     <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class="row mb-5">
	<div class="col-md-4">
		<%= link_to 'Back', posts_path, class: "btn btn-secondary mb-3" %>
		<div class="card">
			<div class="card-header">
        <h5 class='card-title mb-0'>Editing Post</h5>
      </div>
			<div class="card-body">
				<%= render 'form', post: @post %>
			</div>
			<div class="card-footer d-grid gap-2">
				<% if @post.published? %>
			     <a href="#"
			       class='btn btn-secondary btn-block'
			       data-reflex='click->PublisherReflex#unpublish'
			       data-post-id='<%= @post.id %>'>
			       Unpublish
			     </a>
			  <% else %>
			     <a href="#"
			       class='btn btn-dark btn-block'
			       data-reflex='click->PublisherReflex#publish'
			       data-post-id='<%= @post.id %>'>
			       Publish
			     </a>
			  <% end %>				
			</div>
		</div>
	</div>
	<div class="col-md-8">
	  <div class="mb-3">
			<%= form_with(model: [@post, @element], html: { class: 'float-start me-2' }) do |form| %>
			  <%= form.hidden_field :element_type, value: 'paragraph' %>
			  <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
				<i class="bi bi-paragraph"></i>
			  <% end %>
			<% end %>
			<%= form_with(model: [@post, @element], html: { class: 'float-start me-2' }) do |form| %>
			  <%= form.hidden_field :element_type, value: 'image' %>
			  <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
				<i class="bi bi-image-fill"></i>
			  <% end %>
			<% end %>
			<%= form_with(model: [@post, @element]) do |form| %>
			  <%= form.hidden_field :element_type, value: 'element_video' %>
			  <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
				<i class="bi bi-file-earmark-play"></i>
			  <% end %>
			<% end %>
	  </div>
		<div class="card">
			<div class="card-header">
				<% if @post.published? %>
	        <b>Published</b> <%= time_ago_in_words(@post.published_at) %> ago
	      <% else %>
	        Unpublished
	      <% end %>
			</div>
			<div class="card-body pt-3">
				<% @post.elements.each do |element| %>
					<% if element.paragraph? %>
						<div class="paragraph mb-3 p-2">
							<div class="paragraph-content">
								<% if element.content.present? %>
									<%= element.content %>
								<% else %>
									Click to add content.
								<% end %>
							</div>
							<div class="paragraph-form d-none">
								<%= form_with(model: [@post, element]) do |form| %>
									<%= form.rich_text_area :content %>
									<div class="mt-3 d-flex justify-content-between">
										<div>
											<%= form.submit "Save", class: 'btn btn-primary' %>
											<a href="#" class="cancel btn btn-secondary">Cancel</a>
										</div>
										<%= link_to 'Delete', post_element_path(@post, element), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" } %>
									</div>
								<% end %>
							</div>
						</div>
					<% elsif element.image? %>
						<div class="mb-2 p-2 image">
							<% if element.image.present? %>
								<%= link_to post_element_path(@post, element), method: :delete, class: "delete-btn btn btn-dark mt-1 float-end", data: { confirm: "Are you sure?"} do %>
									<i class="bi bi-x-lg"></i>
								<% end %>
								<%= image_tag(element.image, width: "100%") %>
							<% else %>	
								<%= form_with(model: [@post, element]) do |form| %>
									<p>image</p>
									<%= form.file_field :image %>
									<div class="mt-3">
										<%= form.submit "Save", class: "btn btn-primary" %>
									</div>
								<% end %>
							<% end %>
						</div>
					<% elsif element.element_video? %>
						<div class="mb-2 p-2 image">
							<% if element.element_video.present? %>
								<video controls style="width: 100%;">
								  <source src="<%= url_for(element.element_video) %>">
								</video>
								<div class="mt-2">
									<%= link_to 'Delete', post_element_path(@post, element), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" } %>
								</div>
							<% else %>	
								<%= form_with(model: [@post, element]) do |form| %>
									<p>video</p>
									<%= form.file_field :element_video %>
									<div class="mt-3">
										<%= form.submit "Save", class: "btn btn-primary" %>
									</div>
								<% end %>
							<% end %>
						</div>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/authors/posts/index.html.erb
<h4 class="d-flex justify-content-between mb-4">
  <span>Posts</span>
  <%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
</h4>
<% @posts.each do |post| %>
  <%= link_to edit_post_path(post), class: "text-decoration-none" do %>
    <div class="card mb-3">
      <div class="card-body">
        <div class="ard-title text-dark mb-1"><%= post.title %></div>
        <p class="text-secondary mb-0"><%= post.description %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/authors/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/authors/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.published %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @post.published_at %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/layouts/_footer.html.erb
<footer>
  <p><%= image_pack_tag "media/images/ZikTeam.jpeg", height: "55px" %>     <span class="copyright">Zikteam Consult</span></p> 
  <div class="footer-socials">
  
  </div>
  <div class="copyright">
    Copyright 2020 © joshkabs
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <div class="container">
    <nav id="main-nav" class="flex items-center justify-between">
      <div class="left flex items-center">
        <div class="branding">
          <%= image_pack_tag "media/images/ZikTeam.jpeg", height: "65px" %> 
        </div>
	      <div>
	        <a href="#">Home</a>
	        <a href="#about">About</a>
	        <a href="#services">Services</a>
          <%= link_to "Posts", posts_path %>
	        <a href="#work">Work</a>
	        <a href="#blog">Blog</a>
	      </div>
	    </div>
	    <div class="right">
	      <button class="btn btn-primary btn-lg" id="btn-nav1">Contact</button>
	    </div>
	  </nav>
      <div class="hero flex items-center justify-between">
        <div class="left flex-1 flex justify-center">
          <%= image_pack_tag 'media/images/man.png' %>
        </div>
      <div class="right flex-1">
        <h6>Rudy Zikianda</h6>
        <h1>I’m an <span>Economist</span></h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod tempor incididunt ut
          labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco
          laboris
          nisi ut aliquip ex ea commodo consequat</p>
        <div>
          <button class="btn btn-secondary " id="btn-nav2">DOWNLOAD CV</button>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zikteam1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zikteam1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light authors">
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/readers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zikteam1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <div class="site-main-wrapper">
      <%= render "layouts/navbar" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/readers/home/_about.html.erb
<section id="about" class="about">
  <div class="container flex items-center about-inner-wrap">
    <div class="flex-1">
     	<%= image_pack_tag 'media/images/man-2.png' %>
    </div>
    <div class="flex-1 right">
      <h1>About <span>Me</span></h1>
      <h3>Hello! i’m Rudy Zikianda.</h3>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod tempor incididunt ut
      labore et
      dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut
      aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet consectetur adipisicing elit sed do
      eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
      <div class="social">
        <a href="#"><%= image_pack_tag 'media/images/pintrest.svg' %></a>
        <a href="#"><%= image_pack_tag 'media/images/facebook.svg' %></a>
        <a href="#"><%= image_pack_tag 'media/images/twitter.svg' %></a>
        <a href="#"> <%= image_pack_tag 'media/images/pintrest.svg' %></a>
      </div>
    </div>
  </div>
</section>

app/views/readers/home/_contact.html.erb
<section class="contact bg-light" id="contact">
  <div class="container">
    <h1 class="section-heading">Contact <span>Us</span></h1>
    <p>We provide high standar clean website for your business solutions</p>
    <div class="card-wrapper">
      <div class="card" style="height: 350px;">
       	<%= image_pack_tag 'media/images/phone-2.svg' %>  <h1>Call Us On</h1>
        <h6>+985 123 7856</h6>
      </div>
      <div class="card" style="height: 350px;">
        <%= image_pack_tag 'media/images/msg.svg' %> 
        <h1>Email Us At</h1>
        <h6>support@companyname.com</h6>
      </div>
      <div class="card" style="height: 350px;">
        <%= image_pack_tag 'media/images/phone-2.svg' %>
        <h1>Visit Office</h1>
        <h6>99 S.t Jomblo Park Pekanbaru 28292. Indonesia</h6>
      </div>
    </div>
    <br>

    <form action="">
      <div class="input-wrap">
        <input type="text" placeholder="Your Name *">
        <input type="email" placeholder="Your Email *">
      </div>
      <div class="input-wrap-2">
        <input type="text" placeholder="Your Subject...">
        <textarea name="" id="" cols="30" rows="10" placeholder="Your Message..."></textarea>
      </div>
      <div class="btn-wrapper">
        <button class="btn btn-primary">Send Message</button>
      </div>
    </form>
  </div>
</section>

app/views/readers/home/_services.html.erb
<section id="services" class="services">
  <div class="container">
    <h1 class="section-heading"><span>Our </span>Services</h1>
    <p>We provide high standar clean website for your business solutions</p>
    <div class="card-wrapper">
      <div class="card">
     		<%= image_pack_tag 'media/images/brush.svg' %>
        <h2>Graphic Design</h2>
        <p>There are many variations of passages of but the majority have suffered alteration in some form.</p>
      </div>
      <div class="card">
       	<%= image_pack_tag 'media/images/code.svg' %>
        <h2>Graphic Design</h2>
        <p>There are many variations of passages of but the majority have suffered alteration in some form.</p>
      </div>
      <div class="card">
       	<%= image_pack_tag 'media/images/bag.svg' %>
        <h2>Graphic Design</h2>
        <p>There are many variations of passages of but the majority have suffered alteration in some form.</p>
      </div>
      <div class="card">
       	<%= image_pack_tag 'media/images/desktop.svg' %>
        <h2>Graphic Design</h2>
        <p>There are many variations of passages of but the majority have suffered alteration in some form.</p>
      </div>
      <div class="card">
       	<%= image_pack_tag 'media/images/media.svg' %>
        <h2>Graphic Design</h2>
        <p>There are many variations of passages of but the majority have suffered alteration in some form.</p>
      </div>
      <div class="card">
       	<%= image_pack_tag 'media/images/phone.svg' %>
        <h2>Graphic Design</h2>
        <p>There are many variations of passages of but the majority have suffered alteration in some form.</p>
      </div>
    </div>
  </div>
</section>

app/views/readers/home/index.html.erb
<%= render "readers/home/about" %>

<%= render "readers/home/services" %>
    
<section id="blog" class="blog">
  <div class="container">
    <h1 class="section-heading"><span>Our</span> Blog</h1>
    <p>We provide high standar clean website for your business solutions</p>
    <div class="card-wrapper">
      <div class="card">
        <div class="img-wrapper">
         	<%= image_pack_tag 'media/images/article-ph-1.png' %>                  
        </div>
        <div class="card-content">
          <a href="#">
            <h1>Occusamus et iusto odio</h1>
          </a>
          <span>May 12, 2017</span>
          <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
          nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          mollit anim id est laborum.</p>
          <a href="#">Read More</a>
        </div>
      </div>
      <div class="card">
        <div class="img-wrapper">
          <%= image_pack_tag 'media/images/article-ph-1.png' %>
        </div>
        <div class="card-content">
          <a href="#">
            <h1>Occusamus et iusto odio</h1>
          </a>
          <span>May 12, 2017</span>
          <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          mollit anim id est laborum.</p>
          <a href="#">Read More</a>
        </div>
      </div>
      <div class="card">
        <div class="img-wrapper">
          <%= image_pack_tag 'media/images/article-ph-1.png' %>
        </div>
        <div class="card-content">
          <a href="#">
            <h1>Occusamus et iusto odio</h1>
          </a>
          <span>May 12, 2017</span>
          <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          mollit anim id est laborum.</p>
          <a href="#">Read More</a>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render "readers/home/contact" %>
        
  